image: Visual Studio 2017
version: 18.02.2-build{build}
environment:
  version: 18.02.2
install:
- ps: >-
    mkdir $env:TEMP\openloco

    Invoke-WebRequest https://github.com/OpenRCT2/OpenLoco-Dependencies/releases/download/v1.0.0/openloco.dependencies.1.0.0.nupkg -OutFile $env:TEMP\openloco\openloco.dependencies.1.0.0.nupkg

    Get-ChildItem $env:TEMP\openloco

    nuget install OpenLoco.Dependencies -Source $env:TEMP\openloco -OutputDirectory packages

    $env:GIT_DESCRIBE = (git describe HEAD | sed -E "s/-g.+$//")
configuration: Release
build:
  verbosity: minimal
after_build:
- ps: >-
    New-Item -ItemType Directory artefacts | Out-Null

    Copy-Item CHANGELOG.md,LICENSE,bin\*.dll artefacts

    Copy-Item loco.exe artefacts\openloco.exe

    Push-Location artefacts

    7z a -tzip -mx9 -mtc=off -r openloco-v${env:version}-win32.zip *

    Pop-Location

artifacts:
- path: 'artefacts\openloco-v$(version)-win32.zip'
deploy:
  provider: GitHub
  auth_token:
    secure: 49K/y43epwh5Sb8uY1l/TbIFRPcEq6fraQaYGS0bgWQJfONznd6hCqPUCg7WSX16
  artifact: artefacts\openloco-v$(version)-win32.zip
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
